### ISSUE TITLE
runtime issues

### ISSUE THREAD

**Issue by arpit15** [Rancho-zhao/FOTS#1]
I used `Python 3.10.13`. Apparently the `attrdict` package is not maintained anymore and I needed to do a monkey patch as mentioned [here](https://stackoverflow.com/a/74356559)

I face the following error now
```
FileNotFoundError: [Errno 2] No such file or directory: './utils/utils_data/ini_depth_extent_gelsight.npy'
```

Can the authors kindly update the repository with the appropriate files?

**Comment by Rancho-zhao** [comment]
Thank you for pointing out the error, I have fixed it.
