### ISSUE TITLE
Color2NormalDataset is missing

### ISSUE THREAD

**Issue by Marsilea149** [Rancho-zhao/FOTS#2]
Hi, 

I am trying to run the calibration procedure with gelsight mini. It seems that you did not include the class: Color2NormalDataset(). So I could not run "from src.train import MLP, Color2NormalDataset" in train_mlp.py. I found it in digit-depth repository: https://github.com/vocdex/digit-depth/blob/main/digit_depth/train/color2normal_dataset.py#L6 Is it the right one? Thanks!

**Comment by Rancho-zhao** [comment]
Yes, you're right. I'll fixed this problem later. You can also use color2normal_dataset.py file in digit -depth.
