### ISSUE TITLE
Robotic manipulation implementaion

### ISSUE THREAD

**Issue by ZJU-PLP** [Rancho-zhao/FOTS#3]
Hi,
Would you mind sharing the code of robotic manipulation implementation to reproduce the results of Fig. 8(a) in your paper?

**Comment by Rancho-zhao** [comment]
Sorry, I couldn't share the code currently, which is related to my future work. But this part mainly refers to [TactileSimulation](https://github.com/eanswer/TactileSimulation) and [GelSightMujoco](https://github.com/rlamprell/GelSightMujoco).

**Comment by Rancho-zhao** [comment]
Hi, I have added a new FOTS-mujoco branch, which includes an example of FOTS simulation model in MuJoCo. Hope it can help you!

**Comment by ZJU-PLP** [comment]
> Hi, I have added a new FOTS-mujoco branch, which includes an example of FOTS simulation model in MuJoCo. Hope it can help you!

Ok, I see. Thanks for your nice sharing.

**Comment by Steven-ZY** [comment]
@ZJU-PLP Hello! It's a pleasure to meet you. I’m from THU, and also researching tactile-based robotic manipulation in MuJoCo. My QQ number is 864317672, and can we have more in-depth discussions? Looking forward to your reply!
