### ISSUE TITLE
What is "gel_pad" variable and how to get it?

### ISSUE THREAD

**Issue by Marsilea149** [Rancho-zhao/FOTS#5]
Hi Rancho,

Thanks for your nice work! I am trying to test your repository with my Gelsight Mini sensor. 

In particular, I am trying to run "fots_test.py", I am wondering what is the "gel_pad" variable exactly? 
https://github.com/Rancho-zhao/FOTS/blob/5bcde04c6fadee1406ea96d01cbde0b9cedfe736/fots_test.py#L22 
I see in the code above you load it from https://github.com/Rancho-zhao/FOTS/blob/main/utils/utils_data/gelsight_pad.npy, but where does this file come from? How can I get this file for my gelsight mini sensor?

Thank you very much!

**Comment by Rancho-zhao** [comment]
Well, gel_pad is related to the surface shape of elastomers. For example, the surface of gelsight mini is flat, so you can just set gel_pad = 0. If using DIGIT with a non-flatten surface, you need to obtain the height map of its surface using the 3d model of its elastomer.
