### ISSUE TITLE
Update "params.py" for Gelsight Mini

### ISSUE THREAD

**Issue by Marsilea149** [Rancho-zhao/FOTS#6]
Hi Rancho,

I am trying to use your code base with gelsight mini sensor. In, particular, I am trying to run "fots_test.py". I saw that you are using ["params.py"](https://github.com/Rancho-zhao/FOTS/blob/main/params.py) to set the parameters related to the tactile sensor. Could you please share about how do you get the "optical render params"
```
# optical render params
pyramid_kernel_size = [51, 21, 11, 5]#[11, 11, 11, 11, 11, 5] 
kernel_size = 5
```
and how do you get the other parameter values 
```
## GelSight
N = 11
M = 9
x0 = 26
y0 = 15
dx = 29
dy = 26
```
Thank you very much for sharing!

**Comment by Rancho-zhao** [comment]
The optical render params are just the parameters of Gaussian filtering, which can be set by yourself, and you can try changing them to achieve better results. 

As for other parameters, they are related to your own sensor. N, M represent the number of rows and columns of markers, respectively. x0, y0, represent the coordinates of the first marker in the upper left corner. And dx, dy represent the x-y spacing value between markers.
