### ISSUE TITLE
The example env_test.py in FOTS-mujoco branch doesn't work. 

### ISSUE THREAD

**Issue by Junyu-Zhu** [Rancho-zhao/FOTS#8]
Hi, 
I've tried the example code env_test.py in FOTS-mujoco brance, but it shows 

AttributeError: 'MyViewer' object has no attribute 'render_new'

And it seems the class MyViewer in mocap_utils.py is incomplete. Can you help me check this error? Thanks a lot.

**Comment by Rancho-zhao** [comment]
Please follow the first step in the **Usage** section of README.

**Comment by Junyu-Zhu** [comment]
It works, it's my bad miss the introduction at first step, thanks a lot.
